### ISSUE TITLE
Animation speed

### ISSUE THREAD

**Issue by cassionandi** [KPS250/RadialProgress#1]
Hi!

I've been studying your code and I wonder how to manage to control de speed of the second Gauge.

Thanks

**Comment by KPS250** [comment]
You can control the speed with  the data interval in loop( i=i+5). Choose a value lower than 5 for slowing it down or a higher value for increasing the speed.

You can also refer my medium post on it : [https://medium.com/@KPS250/custom-radial-progress-indicator-in-xamarin-forms-c7ed81840c1e](url)

// Animating the Progress of Radial Gauge
async void animateProgress(int progress)
    {
        sw_listToggle.IsEnabled = false;
        sweepAngleSlider.Value = 1;

        // Looping at data interval of 5
        for (int i = 0; i < progress; i=i+5)  // Control the Speed Here
        {
            sweepAngleSlider.Value = i;
            await Task.Delay(3);
        }

        sweepAngleSlider.Value = progress;
        sw_listToggle.IsEnabled = true;

    }

**Comment by KPS250** [comment]
It seems that the above comment should answer your query. Closing this issue:)
